### ISSUE TITLE
播放视频的时候黑屏

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#10]
大佬帮忙看下这个问题，突然间所有视频都不放不了了，只有声音，没有图像，log打印的这些信息
User-Agent: ijkplayer

Accept: */*

Range: bytes=1813795503-

Connection: close

Host: 192.168.3.6:5000

Icy-MetaData: 1

[IJKMEDIA]aout_pause_audio(1)
[IJKMEDIA]push old audio frame:1
[IJKMEDIA]ijkmp_get_msg: FFP_MSG_SEEK_COMPLETE
[IJKMEDIA]audio force reset accurate seek time
[IJKMEDIA]audio accurate_seek start, is->seek_pos=1694177000, audio_clock=1693.919667, estimate drop=7, is->accurate_seek_start_time = 1709794325475
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]ffp_toggle_buffering_l: end
[IJKMEDIA]aout_pause_audio(0)
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek waiting
[IJKMEDIA]audio accurate_seek is timeout, is->drop_aframe_count=1, now = 1709794330477, audio_clock = 1693.919667
[IJKMEDIA]Using s16p internally between filters
[IJKMEDIA]Matrix coefficients:
FL: FL:0.414214 FR:0.000000 FC:0.292893 LFE:0.000000 SL:0.292893 SR:0.000000 
FR: FL:0.000000 FR:0.414214 FC:0.292893 LFE:0.000000 SL:0.000000 SR:0.292893 
[IJKMEDIA]avcodec/Audio: first frame decoded

**Comment by debugly** [comment]
现在如何了？换个设备试试呢？

**Comment by zdw19840929** [comment]
> 现在如何了？换个设备试试呢？
这个不是百分百出现，具体什么时候能复现我也不太清楚，因为那次之后就没出现过了😂

**Comment by debugly** [comment]
需要提供更多的日志来分析。

**Comment by zdw19840929** [comment]
> 需要提供更多的日志来分析。

好的 等我再次复现的时候把日志都打出来再看看 谢谢大佬的解答
