### ISSUE TITLE
上传到Connect时出错

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#11]
大佬 app上传的时候出错，麻烦您看下
![截屏2024-03-05 21 53 04](https://github.com/debugly/ijkplayer/assets/4941590/8ca600e2-afbb-4516-89e2-55d301eae915)

**Comment by zdw19840929** [comment]
我把texImageIOSSurface方法改了个名字就可以了

**Comment by debugly** [comment]
改成什么了？

**Comment by zdw19840929** [comment]
> 改成什么了？

就把texImageIOSSurface后面加了个s -> texImageIOSSurfaces

**Comment by debugly** [comment]
这样不行啊

```
- (BOOL)texImageIOSurface:(IOSurfaceRef)arg1 target:(unsigned long long)arg2 internalFormat:(unsigned long long)arg3 width:(unsigned)arg4 height:(unsigned)arg5 format:(unsigned long long)arg6 type:(unsigned long long)arg7 plane:(unsigned)arg8 invert:(BOOL)arg9;
```
这是个私有方法，你改个名字的话，调用时找不到这个方法不崩溃吗？
抓紧找个低于 iOS 11 的系统测下。

**Comment by zdw19840929** [comment]
> 这样不行啊
> 
> ```
> - (BOOL)texImageIOSurface:(IOSurfaceRef)arg1 target:(unsigned long long)arg2 internalFormat:(unsigned long long)arg3 width:(unsigned)arg4 height:(unsigned)arg5 format:(unsigned long long)arg6 type:(unsigned long long)arg7 plane:(unsigned)arg8 invert:(BOOL)arg9;
> ```
> 
> 这是个私有方法，你改个名字的话，调用时找不到这个方法不崩溃吗？ 抓紧找个低于 iOS 11 的系统测下。

大佬我也发现这个iOS11系统一下会崩溃，但我最低支持iOS15，而且实在找不到iOS11以下系统的手机了。。。

**Comment by debugly** [comment]
最低支持 iOS15 没事的，压根逻辑不会走到这里来，想要在高系统版本测试的话也简单：

```
if (@available(macOS 10.13, ios 11.0, *)) {
    glView = [[IJKMetalView alloc] initWithFrame:rect];
} else {
    glView = [[IJKSDLGLView alloc] initWithFrame:rect];
}
```

把 `ios 11.0` 改大些就行了，比如：`ios 21.0` 。

**Comment by zdw19840929** [comment]
> 最低支持 iOS15 没事的，压根逻辑不会走到这里来，想要在高系统版本测试的话也简单：
> 
> ```
> if (@available(macOS 10.13, ios 11.0, *)) {
>     glView = [[IJKMetalView alloc] initWithFrame:rect];
> } else {
>     glView = [[IJKSDLGLView alloc] initWithFrame:rect];
> }
> ```
> 
> 把 `ios 11.0` 改大些就行了，比如：`ios 21.0` 。

谢谢大佬耐心指点，我晚上回去试试
