### ISSUE TITLE
iOS代码编译时报错instruction requires: dotprod

### ISSUE THREAD

**Issue by applicationHe** [debugly/ijkplayer#15]
Macbook M2芯片
执行./compile-any.sh build all
报错如下:
<inline asm>:11:1: error: instruction requires: dotprod
udot  v0.4s, v4.166, v16.16b
^
error: cannot compile inline asm <inline asm›:12:1: error: instruction requires: dotprod
udot  v1.4s, v5.16b, v16.16b
^
error: cannot compile inline asm <inline asm>:13:1: error: instruction requires: dotprod
udot  v2.4s, V6. 16b, V16.16b
^
error: cannot compile inline asm <inline asm>:14:1: error: instruction requires: dotprod
udot  v3.4s, v7.16b,V16.16b

**Comment by debugly** [comment]
我在M1上无法复现这个问题，参考下这个 issue 吧：https://github.com/official-stockfish/Stockfish/issues/4408

**Comment by criswonder** [comment]
求助，我也有这个问题，错误日志如下。多谢帮忙看下要怎么解决或者是提供什么信息

➜  ios git:(latest) ✗ ./compile-any.sh build libyuv
support thread count:8
Xcode 15.2 Build version 15C500b
------------------------------------------
XC_PLAT         : [ios]
XC_CMD          : [build]
XC_VENDOR_LIBS  : [libyuv]
XC_TARGET_ARCHS : [x86_64 arm64]
XC_OPTS         : []
XC_FORCE_CROSS  : [true]
------------------------------------------
===[build libyuv]====================
=== [./do-compile/any.sh] check env begin===
XC_CMD:build
XC_TARGET_ARCHS:x86_64 arm64
LIPO_LIBS:libyuv
LIB_NAME:libyuv
XC_OPTS:
XC_FORCE_CROSS:true
===check env end===
[*] check depends bins:
====================
=== [./do-compile/libyuv.sh] check env begin===
XC_ARCH:x86_64
XC_BUILD_SOURCE:/Users/andy/source/personal/github-projects/ijkplayer_debugly/shell/apple/../build/src/ios/libyuv-x86_64
XC_BUILD_NAME:libyuv-x86_64
XC_DEPLOYMENT_TARGET:-mios-simulator-version-min=11.0
XCRUN_SDK_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk
XC_BUILD_PREFIX:/Users/andy/source/personal/github-projects/ijkplayer_debugly/shell/apple/../build/product/ios/libyuv-x86_64
THREAD_COUNT:8
XC_OPTS:
===check env end===
[*] cross compile, on arm64 compile ios x86_64.
CC: xcrun -sdk iphonesimulator clang
CXX: xcrun -sdk iphonesimulator clang++
CFLAGS: -arch x86_64 -mios-simulator-version-min=11.0 -fembed-bitcode -Os -fomit-frame-pointer -Iinclude/ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk

----------------------
[*] configurate libyuv
----------------------
----------------------
[*] compile libyuv
----------------------
/Users/andy/source/personal/github-projects/ijkplayer_debugly/shell/apple

=== [./do-compile/libyuv.sh] check env begin===
XC_ARCH:arm64
XC_BUILD_SOURCE:/Users/andy/source/personal/github-projects/ijkplayer_debugly/shell/apple/../build/src/ios/libyuv-arm64
XC_BUILD_NAME:libyuv-arm64
XC_DEPLOYMENT_TARGET:-miphoneos-version-min=11.0
XCRUN_SDK_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk
XC_BUILD_PREFIX:/Users/andy/source/personal/github-projects/ijkplayer_debugly/shell/apple/../build/product/ios/libyuv-arm64
THREAD_COUNT:8
XC_OPTS:
===check env end===
[*] cross compile, on arm64 compile ios arm64.
CC: xcrun -sdk iphoneos clang
CXX: xcrun -sdk iphoneos clang++
CFLAGS: -arch arm64 -miphoneos-version-min=11.0 -fembed-bitcode -Os -fomit-frame-pointer -Iinclude/ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk

----------------------
[*] configurate libyuv
----------------------
----------------------
[*] compile libyuv
----------------------
<inline asm>:14:1: error: instruction requires: dotprod
udot        v4.4s, v0.16b, v6.16b
^
error: cannot compile inline asm
<inline asm>:15:1: error: instruction requires: dotprod
udot        v5.4s, v1.16b, v6.16b
^
error: cannot compile inline asm
<inline asm>:10:1: error: instruction requires: dotprod
udot        v4.4s, v0.16b, v0.16b
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v5.4s, v1.16b, v1.16b
^
error: cannot compile inline asm
4 errors generated.
make: *** [source/compare_neon64.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by debugly** [comment]
我这里使用Xcode15.3 编译 libyuv 也出错了，不过和你那不一样；使用最新代码先clean, 然后重新编译下试试。

**Comment by zdw19840929** [comment]
@debugly 大佬看下编译libyuv的时候我也报错了，拉的是最新的脚本，XCode15.3
![截屏2024-05-13 23 37 26](https://github.com/debugly/ijkplayer/assets/4941590/d946e8c2-9e2b-4696-aa7f-dab2da37755b)

**Comment by debugly** [comment]
如果没有修改源码，不要编译这些库，浪费时间！
我早已预编译好了这些依赖库，直接下载到本地使用就行：

```shell
cd shell 
#安装iOS和macOS平台所有的依赖库
./install-pre-any.sh all all
#安装iOS平台所有的依赖库
./install-pre-any.sh ios all
#安装macOS平台所有的依赖库
./install-pre-any.sh macos all
```
根据开发的平台安装就行。

如果不修改ijk的源码，直接下载预编译好的 framework 放进工程就行：

https://github.com/debugly/ijkplayer/releases

**Comment by zdw19840929** [comment]
感谢大佬的回复，用上面的方法已经可以顺利编译了 @debugly

**Comment by huaibaobao2017** [comment]
同样的报错。大佬能编译一个支持samba的版本吗？

**Comment by debugly** [comment]
实际上当前没有使用libyuv，可以不用编译它。
正在测试即将发布的版本，没有时间帮你编译samba呢。
