### ISSUE TITLE
[Feature Request] tvOS支持

### ISSUE THREAD

**Issue by hsuyelin** [debugly/ijkplayer#20]
请问有移植到 tvOS 的计划么

**Comment by debugly** [comment]
目前没有这个计划。

**Comment by hsuyelin** [comment]
那将来会有计划么 @debugly

**Comment by debugly** [comment]
你有什么需求？

**Comment by hsuyelin** [comment]
想在集成ijkplayer开发一个app包含tvOS，目前试了大佬一致的播放器完全满足我的要求，如果tvOS再很长时间内都不会支持的话，我就考虑再在APP中集成VLC或者MPV来完成，这样的话就增加了包体积

**Comment by debugly** [comment]
可以考虑移植。

**Comment by hsuyelin** [comment]
> 可以考虑移植。

期待ing...

**Comment by zdw19840929** [comment]
期待大佬的tvOS版本 @debugly

**Comment by debugly** [comment]
tvOS is coming...

**Comment by hsuyelin** [comment]
> @hsuyelin tvOS已经支持了。

帅气
