### ISSUE TITLE
[Discussions] 问题探讨

### ISSUE THREAD

**Issue by hsuyelin** [debugly/ijkplayer#21]
请问有什么办法可以加载本地字幕么，在demo工程按照如下方式加载并不生效

```objectivec
NSString *subtitlePath = [[NSBundle mainBundle] pathForResource:@"chs" ofType:@"srt"];
[self.player loadSubtitleOnly:[NSURL fileURLWithPath:subtitlePath]];
```

**Comment by debugly** [comment]
使用 loadThenActiveSubtitle 方法，会立马激活。
使用 loadSubtitleOnly 或者 loadSubtitlesOnly 只是挂载，没有激活；如需激活配合 exchangeSelectedStream 方法使用。
这样你可以先挂N个字幕，然后根据需要让用户去切换。
