### ISSUE TITLE
[Feature Request] 返回FLAC内嵌歌词

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#22]
大佬能不能将FLAC内嵌歌词返回一下呢
http://username:password@opds-server-url.com
https://zdw1984:19840929Zdw@zhangdawei.synology.me:8032/opds/

618活动现已开启！
感谢大家一直以来的支持。这次降价促销活动仅限于618期间，对之前购买的用户表示歉意。
为了回馈老用户们的支持，我将通过增加更加有用和便捷的功能来表达我们的谢意。
感谢您的理解与支持！

if (gesture.state == .began) {
                        self.handType = .volumeChange
                    }

background:url('webapi/entry.cgi?api=SYNO.Core.Package.Thumb.Server&method=get&version=1&SynoToken=buepRMMtBYps6&name=%22CloudSync%22&ver=%222.7.0-2610%22&link=%22https%3A%2F%2Fglobal.synologydownload.com%2Fdownload%2FPackage%2Fimg%2FCloudSync%2F2.7.0-2610%2Fthumb_72.png%22&size=64&bls=true');background-size:64px;

[IJKMEDIA]Option safe not found.
[IJKMEDIA]max_frame_duration: 10.000
[IJKMEDIA]Input #0, flac, from 'http://116.196.124.216:34836/fbdownload/%E6%9C%9B-%E4%BB%BB%E7%84%B6.flac?dlink=%222F6D757369632FE58AA9E79CA02FE69C9B2DE4BBBBE784B62E666C6163%22&_sid=3knqqmRX0nvFIlcYmUwPIHG7dqbtLX9sgHnQvDkiWW8XTiuN90K8v1esY60YFiV71PZjBfI-UpaoRgeMyReU_Y&mime=1':
[IJKMEDIA]  Metadata:
    ALBUM           : 望
    album_artist    : 任然
    ARTIST          : 任然
    ENCODER         : Lavf58.20.100
    LYRICS          : [by:天琴实验室AI生成v1.0]
                    : [00:00.00]﻿望-任然
                    : [00:01.24]
                    : [00:02.48]词Lyricist：曾小凡
                    : [00:03.72]曲Composer：曾小凡
                    : [00:04.96]编曲Arranger：邱沐阳
                    : [00:06.21]吉他Guitar：Tommy Wu
                    : [00:07.45]和声Backing Vocalist：皎月/小手鹅
                    : [00:08.69]混音工程师Mixing Engineer：殇小谨
                    : [00:09.93]母带工程师Mastering Engineer：殇小谨
                    : [00:11.17]配唱制作人Vocal Producer：kent 王健
                    : [00:12.42]制作人Music Producer：殇小谨
                    : [00:13.66]监制Musical Supervisor：三千
                    : [00:14.90]OP：北京千和世纪文化传播有限公司
                    : [00:16.14]SP：千和世纪×RR
                    : [00:17.38]「版权所有未经许可请勿使用」
                    : [00:18.63]月亮有一个缺
                    : [00:22.38]等着云去填
                    : [00:26.10]风与心事周旋
                    : [00:29.85]吹花我的眼
                    : [00:33.63]高楼承载疲倦一天又一天
                    : [00:41.55]怀念的是从前
                    : [00:44.70]和玩伴肩并肩
                    : [00:48.66]路途不算太远
                    : [00:52.29]晃眼几十年
                    : [00:56.04]熟悉模糊的脸
                    : [00:59.82]存放在心间
                    : [01:03.57]回忆的幻灯片一眼又一眼
                    : [01:11.55]我是不是丢失了从前
                    : [01:18.09]回头望呀想呀叹呀念呀
                    : [01:26.49]还记得曾说过快长大呀不想回家
                    : [01:33.15]回头望呀泪呀苦呀累呀
                    : [01:41.55]这是你来时走的路呀
                    : [02:03.66]路途不算太远
                    : [02:07.32]晃眼几十年
                    : [02:11.04]熟悉模糊的脸
                    : [02:14.82]存放在心间
                    : [02:18.57]回忆的幻灯片一眼又一眼
                    : [02:26.64]我是不是丢失了从前
                    : [02:33.12]回头望呀想呀叹呀念呀
                    : [02:41.58]还记得曾说过快长大呀不想回家
                    : [02:48.18]回头望呀泪呀苦呀累呀
                    : [02:56.61]这是你来时走的路啊
                    : [03:03.51]望呀想呀叹呀念呀
                    : [03:11.64]还记得曾说过快长大呀不想回家
                    : [03:18.24]回头望呀泪呀苦呀累呀
                    : [03:28.44]这是你来时走的路呀
    TITLE           : 望
  Duration: 00:03:57.18, start: 0.000000, bitrate: 747 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 800x800 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn (attached pic)
[IJKMEDIA]    Metadata:
      comment         : Cover (front)
[IJKMEDIA]AudioCodec: avcodec, flac
[IJKMEDIA]VideoCodec: avcodec, mjpeg
[IJKMEDIA]fps: 90000.000000 (normal)

[望-任然.flac.zip](https://github.com/user-attachments/files/15755477/-.flac.zip)

**Comment by debugly** [comment]
可以，预计下下个版本支持。

**Comment by debugly** [comment]
已经支持，使用 https://github.com/debugly/ijkplayer/releases/tag/0.11.3 试试，下次我没支持前先不要关闭 issue。
