### ISSUE TITLE
xcode15.4 编译错误

### ISSUE THREAD

**Issue by chinaxxren** [debugly/ijkplayer#23]
(base) ➜  ios git:(master) ✗ ./compile-any.sh build all
support thread count:12
Xcode 15.4 Build version 15F31d
------------------------------------------
XC_PLAT         : [ios]
XC_CMD          : [build]
XC_VENDOR_LIBS  : [libyuv openssl opus dav1d ffmpeg]
XC_TARGET_ARCHS : [x86_64 arm64]
XC_OPTS         : []
XC_FORCE_CROSS  : [true]
------------------------------------------
===[build libyuv]====================
=== [./do-compile/any.sh] check env begin===
XC_CMD:build
XC_TARGET_ARCHS:x86_64 arm64
LIPO_LIBS:libyuv
LIB_NAME:libyuv
XC_OPTS:
XC_FORCE_CROSS:true
===check env end===
[*] check depends bins: 
====================
=== [./do-compile/libyuv.sh] check env begin===
XC_ARCH:x86_64
XC_BUILD_SOURCE:/Users/chinaxxren/Study/New/ijkplayer2/shell/apple/../build/src/ios/libyuv-x86_64
XC_BUILD_NAME:libyuv-x86_64
XC_DEPLOYMENT_TARGET:-mios-simulator-version-min=11.0
XCRUN_SDK_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk
XC_BUILD_PREFIX:/Users/chinaxxren/Study/New/ijkplayer2/shell/apple/../build/product/ios/libyuv-x86_64
THREAD_COUNT:12
XC_OPTS:
===check env end===
[*] cross compile, on x86_64 compile ios x86_64.
CC: xcrun -sdk iphonesimulator clang
CXX: xcrun -sdk iphonesimulator clang++
CFLAGS: -arch x86_64 -mios-simulator-version-min=11.0 -fembed-bitcode -Os -fomit-frame-pointer -Iinclude/ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk

----------------------
[*] configurate libyuv
----------------------
----------------------
[*] compile libyuv
----------------------
/Users/chinaxxren/Study/New/ijkplayer2/shell/apple

=== [./do-compile/libyuv.sh] check env begin===
XC_ARCH:arm64
XC_BUILD_SOURCE:/Users/chinaxxren/Study/New/ijkplayer2/shell/apple/../build/src/ios/libyuv-arm64
XC_BUILD_NAME:libyuv-arm64
XC_DEPLOYMENT_TARGET:-miphoneos-version-min=11.0
XCRUN_SDK_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk
XC_BUILD_PREFIX:/Users/chinaxxren/Study/New/ijkplayer2/shell/apple/../build/product/ios/libyuv-arm64
THREAD_COUNT:12
XC_OPTS:
===check env end===
[*] cross compile, on x86_64 compile ios arm64.
CC: xcrun -sdk iphoneos clang
CXX: xcrun -sdk iphoneos clang++
CFLAGS: -arch arm64 -miphoneos-version-min=11.0 -fembed-bitcode -Os -fomit-frame-pointer -Iinclude/ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk

----------------------
[*] configurate libyuv
----------------------
----------------------
[*] compile libyuv
----------------------
<inline asm>:14:1: error: instruction requires: dotprod
udot        v4.4s, v0.16b, v6.16b         
^
error: cannot compile inline asm
<inline asm>:15:1: error: instruction requires: dotprod
udot        v5.4s, v1.16b, v6.16b         
^
error: cannot compile inline asm
<inline asm>:10:1: error: instruction requires: dotprod
udot        v4.4s, v0.16b, v0.16b         
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v5.4s, v1.16b, v1.16b         
^
error: cannot compile inline asm
4 errors generated.
make: *** [source/compare_neon64.o] Error 1
make: *** Waiting for unfinished jobs....
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:11:1: error: instruction requires: dotprod
udot        v0.4s, v4.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:12:1: error: instruction requires: dotprod
udot        v1.4s, v5.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:13:1: error: instruction requires: dotprod
udot        v2.4s, v6.16b, v16.16b        
^
error: cannot compile inline asm
<inline asm>:14:1: error: instruction requires: dotprod
udot        v3.4s, v7.16b, v16.16b        
^
error: cannot compile inline asm
32 errors generated.
make: *** [source/row_neon64.o] Error 1

**Comment by debugly** [comment]
参考这个issue: https://github.com/debugly/ijkplayer/issues/15

没有修改三方库源码的话，直接下载预编译库即可。

**Comment by chinaxxren** [comment]
<img width="590" alt="image" src="https://github.com/debugly/ijkplayer/assets/49141798/bf3316c6-1dd7-4bdb-830d-22aa9f75d1f4">
这里写错了，应该是 iOS，不是 macos

**Comment by debugly** [comment]
感谢提醒，已经修复了，下个版本更正。
