### ISSUE TITLE
【iOS端】能否提供TS转MP4的功能接口供外部使用

### ISSUE THREAD

**Issue by mg459046365** [debugly/ijkplayer#25]
你好，将TS视频文件转MP4格式，需要借助FFMPEG的命令，能否提供该功能接口呢。或者说否提供FFMPEG命令接口供外部调用，类似于 https://github.com/kewlbear/FFmpeg-iOS 该库提供的功能

**Comment by debugly** [comment]
可以提供，这个功能跟ijk无关，我可能会把他单独做成一个工具。

**Comment by mg459046365** [comment]
> 可以提供，这个功能跟ijk无关，我可能会把他单独做成一个工具。

谢谢大佬，一直再用哔站的IJKPlayer，最近想切换成大佬的库，但由于用到了FFMPEG的命令工具，暂时只能等大佬提供了开放接口在替换了。非常期待。

**Comment by mg459046365** [comment]
> 可以提供，这个功能跟ijk无关，我可能会把他单独做成一个工具。

感谢大佬。一直再用IJKPlayer，最近想切换成大佬的库，但由于用到了FFMPEG的命令工具，暂时只能等大佬提供了开放接口在替换了，希望大佬能集成到库里面。非常期待。

**Comment by debugly** [comment]
B 站 IJKPlayer 也没有提供 FFmpeg 工具，之前你是怎么用的呢？现在仍旧这么用是否可以？

**Comment by mg459046365** [comment]
> B 站 IJKPlayer 也没有提供 FFmpeg 工具，之前你是怎么用的呢？现在仍旧这么用是否可以？
B站也没有，我们这边自己在IJKPayer的基础上自己加的这个功能，然后自行编译到IKPlayer库中使用，现在仍旧在使用呢。

**Comment by mg459046365** [comment]
> B 站 IJKPlayer 也没有提供 FFmpeg 工具，之前你是怎么用的呢？现在仍旧这么用是否可以？

B站也没有，我们这边自己在IJKPayer的基础上自己加的这个功能，然后自行编译到IKPlayer库中使用，现在仍旧在使用呢。

**Comment by debugly** [comment]
工具做好了，基于 ffmpeg6.1.1 ，ijkplayer下一次发布就会使用这个版本，你可以先集成试试，下载地址：https://github.com/debugly/ffmpeg-kit/releases/tag/6.1.1-lts-240725144213
如果不满足需求，你可以把需要开启的功能对应的编译选项告诉我，比如：--enable-decoder=h264 等，考虑到包体积所以现在开启的编码器和复用器很少。
