### ISSUE TITLE
怎么监听 metadata 变化?

### ISSUE THREAD

**Issue by zhoudajun-ola** [debugly/ijkplayer#28]
radio 源：http://stream-uk1.radioparadise.com/aac-320
开始播放会打印如下 metadata 相关日志：
[IJKMEDIA]  Metadata:
    icy-br          : 320
    icy-description : DJ-mixed blend of modern and classic rock, electronica, world music, and more. Always 100% commercial-free
    icy-genre       : Eclectic
    icy-name        : Radio Paradise (320k aac)
    icy-pub         : 1
    icy-url         : https://radioparadise.com
    StreamTitle     : Montaigne - Gravity (feat. David Byrne)
    StreamUrl       : http://img.radioparadise.com/covers/l/19255_32719d4a-7ef6-4d38-a1da-0bcf96118848.jpg

如何监听 这个MetaData有变化呢；

**Comment by debugly** [comment]
IJK 当前只解析了通用的一部分Key，如下： 
https://github.com/debugly/ijkplayer/blob/28eb304416622daadb2e38e43a7788f59979a376/ijkmedia/ijkplayer/ijkmeta.h#L30-L77

你列举的这些应该是自己定义的，meta 处理逻辑没有解析。

**Comment by debugly** [comment]
你能告诉我 icy信息多久变化一次吗？我需要测试下

**Comment by debugly** [comment]
icy meta 标准都包含了哪些字段知道吗？

**Comment by debugly** [comment]
已经支持，使用 https://github.com/debugly/ijkplayer/releases/tag/0.11.3 试试。

**Comment by debugly** [comment]
第一次的Meta信息在收到IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification之后可以获取到。
meta信息没更新这个我修复下。

**Comment by debugly** [comment]
用这个包试试 https://github.com/debugly/ijkplayer/releases/download/k0.11.4/IJKMediaPlayerKit.zip

**Comment by debugly** [comment]
你赶的巧，这会刚好有时间
