### ISSUE TITLE
No support for arm64 ios simulator

### ISSUE THREAD

**Issue by openmetrue** [debugly/ijkplayer#3]
Is it possible to add a script to compile ffmpeg libraries for iOS simulator with Apple Silicon?
UPD: OpenGL ES on ARM64 simulators produces a lot of weird crashes, probably need to complete the transition to Metal first

**Comment by debugly** [comment]
When use  Designed for iPhone simulator the SDK is iPhone rather than iphonesimulator, so I think Apple Silicon mac (Designed for iPhone) simulator is equal iPhone。
**does iPhone produces OpenGL ES weird crashes?**
Transition to Metal is going about 2023.

**Comment by debugly** [comment]
develop branch : system version greater than or equal to macOS 10.13 or iOS11.0 auto use Metal render video.
