### ISSUE TITLE
两个404

### ISSUE THREAD

**Issue by trial** [debugly/ijkplayer#33]
readme里json链接是
:podspec => 'https://github.com/debugly/ijkplayer/releases/download/k0.11.3/IJKMediaPlayerKit.spec.json'
实际是
https://github.com/debugly/ijkplayer/releases/download/0.11.3/IJKMediaPlayerKit.spec.json

json里zip包也是404
"source": {
    "http": "https://github.com/debugly/ijkplayer/releases/download/k0.11.3/IJKMediaPlayerKit.zip"
  }

**Comment by debugly** [comment]
感谢反馈，以readme里的为准，已经重新发布了 k0.11.3 版本。
