### ISSUE TITLE
播放 RTMP 格式的流，显示空白，用的最新版本

### ISSUE THREAD

**Issue by 1996GJ** [debugly/ijkplayer#35]
显示日志
===== custom modules begin =====
[0;33mskip     demuxer : ijklivehook (duplicated)
[0m===== custom modules end =====
!!!!!!!!!!
actual: n5.1.4-19-g052f043
expect: n5.1.4-18
!!!!!!!!!!
请问 如何解决

**Comment by debugly** [comment]
我测试了 rtmp 拉流正常，你需要提供一个完整日志。

**Comment by 1996GJ** [comment]
请问 如何开启 日志功能，现在只会打印这两行内容，就没了

**Comment by 1996GJ** [comment]
> 我测试了 rtmp 拉流正常，你需要提供一个完整日志。

请问 如何开启 日志功能，现在只会打印这两行内容，就没了

**Comment by debugly** [comment]
在播放前设置： [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_DEBUG];

**Comment by 1996GJ** [comment]
> 在播放前设置： [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_DEBUG];

[IJKMEDIA]ijkmp_set_inject_opaque(0x302c6bf30)
[IJKMEDIA]ijkmp_set_inject_opaque()=void
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque(0x302c6bf30)
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque()=void
[IJKMEDIA]ijkmp_ios_set_view(glView=0x11c036600)
[IJKMEDIA]ijkmp_ios_set_view(glView=0x11c036600)=void

**Comment by 1996GJ** [comment]
> 在播放前设置： [IJKFFMoviePlayerController setLogLevel:k_IJK_LOG_DEBUG];

[IJKMEDIA]ijkmp_set_inject_opaque(0x302c6bf30)
[IJKMEDIA]ijkmp_set_inject_opaque()=void
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque(0x302c6bf30)
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque()=void
[IJKMEDIA]ijkmp_ios_set_view(glView=0x11c036600)
[IJKMEDIA]ijkmp_ios_set_view(glView=0x11c036600)=void

日志只有 这些，麻烦看下，谢谢

**Comment by debugly** [comment]
调用 setLogHandler 了吗？

**Comment by debugly** [comment]
使用的预编译的framework还是源码？如果是源码的话，调试下 ffp_apple_log_extra_vprint 这个方法，日志会从这个方法输出

**Comment by debugly** [comment]
哪个平台？

**Comment by 1996GJ** [comment]
> 哪个平台？

iPad 上,我也用了 iphone试了,是同样的问题

**Comment by debugly** [comment]
没有设置 setLogHandler 时，默认输出到标准输出，是否日志库重定向了 stdout ？
你现在贴出来的几行日志是Xcode控制台输出的吗？

**Comment by 1996GJ** [comment]
> 没有设置 setLogHandler 时，默认输出到标准输出，是否日志库重定向了 stdout ？ 你现在贴出来的几行日志是Xcode控制台输出的吗？

没做这么复杂的设置，现在只是写了最基础的播放设置，设置完 setLogHandler后，打印的内容和刚才的是一致的，这是我的 RTMP流，您可以试下 是否正常 (rtmp://livepull3.uniview.com/live/210235c4rh3243000324000003365290_h265?txTime=66AB2377&txSecret=2e228f6624fc1bafb8c0d25cd8887362)

**Comment by debugly** [comment]
日志跟是否播放 rtmp 协议无关，具体不知道你那是什么情况了，这个流我试了，没问题哦。

**Comment by debugly** [comment]
我这创建了一个 ios的demo，有日志输出的。
[ios.zip](https://github.com/user-attachments/files/16437115/ios.zip)
pod install 之后，你试试

**Comment by 1996GJ** [comment]
> 我这创建了一个 ios的demo，有日志输出的。 [ios.zip](https://github.com/user-attachments/files/16437115/ios.zip) pod install 之后，你试试

使用您发的 Demo ,可以正常播放，我看看 两者区别，感谢帮助
