### ISSUE TITLE
您好 在获取 视频码率的时候 永远都是 0

### ISSUE THREAD

**Issue by 1996GJ** [debugly/ijkplayer#36]
IJKFFMonitor *monitor
 NSLog(@"bitrate: %lld",self.player.monitor.bitrate);
我在视频播放后，定时获取码率，但是获取的都是 0，请问是不是有别的方式来获取 媒体数据，感谢你的解答

**Comment by debugly** [comment]
对于直播这个情况我明天看下，现在是读取的stream 里的属性。

**Comment by debugly** [comment]
需要什么媒体数据，具体点呢？

**Comment by 1996GJ** [comment]
> IJKFFMonitor

IJKFFMonitor 的 bitrat,码率

**Comment by debugly** [comment]
```
总码率：
NSLog(@"ic bitrate:%d",self.player.monitor.bitrate);
视频码率：
NSLog(@"video bitrate:%@",self.player.monitor.videoMeta[k_IJKM_KEY_BITRATE]);
音频码率：
NSLog(@"audio bitrate:%@",self.player.monitor.audioMeta[k_IJKM_KEY_BITRATE]);
```

实际上 videoMeta 和 AudioMeta 里包含了很多信息，你自己挑着用吧。

**Comment by 1996GJ** [comment]
请问，如果要做 录像功能，是不是要改底层的  ff_ffplay再 重新编译使用

**Comment by 1996GJ** [comment]
> ```
> 总码率：
> NSLog(@"ic bitrate:%d",self.player.monitor.bitrate);
> 视频码率：
> NSLog(@"video bitrate:%@",self.player.monitor.videoMeta[k_IJKM_KEY_BITRATE]);
> 音频码率：
> NSLog(@"audio bitrate:%@",self.player.monitor.audioMeta[k_IJKM_KEY_BITRATE]);
> ```
> 
> 实际上 videoMeta 和 AudioMeta 里包含了很多信息，你自己挑着用吧。

谢谢，我试试 这个

**Comment by debugly** [comment]
> 请问，如果要做 录像功能，是不是要改底层的 ff_ffplay再 重新编译使用

录像可以基于 AVFoundation 的 AVCaptureSession 去做，收到数据后使用 IJKMetalView 显示即可。
跟 ffplay 没啥关系啊。

**Comment by 1996GJ** [comment]
> > 请问，如果要做 录像功能，是不是要改底层的 ff_ffplay再 重新编译使用
> 
> 录像可以基于 AVFoundation 的 AVCaptureSession 去做，收到数据后使用 IJKMetalView 显示即可。 跟 ffplay 没啥关系啊。

是将 直播监控给录制下来，类似于截图，也是可以用AVCaptureSession 么？

**Comment by debugly** [comment]
把使用ijkplayer播放的直播直接保存成视频文件？还是隔一会保存一张图片？

**Comment by 1996GJ** [comment]
> > 请问，如果要做 录像功能，是不是要改底层的 ff_ffplay再 重新编译使用
> 
> 录像可以基于 AVFoundation 的 AVCaptureSession 去做，收到数据后使用 IJKMetalView 显示即可。 跟 ffplay 没啥关系啊。



> 把使用ijkplayer播放的直播直接保存成视频文件？还是隔一会保存一张图片？

将播放的直播进行保存成 视频文件

**Comment by debugly** [comment]
可以实现，有难度，需要基于 FFmpeg 库开发，不需要 AVCaptureSession。

**Comment by 1996GJ** [comment]
> 可以实现，有难度，需要基于 FFmpeg 库开发，不需要 AVCaptureSession。

我也在研究 FFmpegKit，想试试 能不能 直接使用，资料太少了 不好找

**Comment by debugly** [comment]
如果不考虑播放，最简单的方式是直接将 rtsp 直播流保存成 flv ，命令如下：

```
FFmpegSession* session = [FFmpegKit executeAsync:@"-i rtsp://your_rtsp_stream_url -c copy output.flv" withCompleteCallback:^(FFmpegSession* session){
    SessionState state = [session getState];
    ReturnCode *returnCode = [session getReturnCode];

    // CALLED WHEN SESSION IS EXECUTED

    NSLog(@"FFmpeg process exited with state %@ and rc %@.%@", [FFmpegKitConfig sessionStateToString:state], returnCode, [session getFailStackTrace]);

} withLogCallback:^(Log *log) {

    // CALLED WHEN SESSION PRINTS LOGS

} withStatisticsCallback:^(Statistics *statistics) {

    // CALLED WHEN SESSION GENERATES STATISTICS

}];
```

FFmpegKit 可以从这里下载：https://github.com/debugly/ffmpeg-kit/releases/tag/6.1.1-lts-240726170810

**Comment by 1996GJ** [comment]
> 如果不考虑播放，最简单的方式是直接将 rtsp 直播流保存成 flv ，命令如下：
> 
> ```
> FFmpegSession* session = [FFmpegKit executeAsync:@"-i rtsp://your_rtsp_stream_url -c copy output.flv" withCompleteCallback:^(FFmpegSession* session){
>     SessionState state = [session getState];
>     ReturnCode *returnCode = [session getReturnCode];
> 
>     // CALLED WHEN SESSION IS EXECUTED
> 
>     NSLog(@"FFmpeg process exited with state %@ and rc %@.%@", [FFmpegKitConfig sessionStateToString:state], returnCode, [session getFailStackTrace]);
> 
> } withLogCallback:^(Log *log) {
> 
>     // CALLED WHEN SESSION PRINTS LOGS
> 
> } withStatisticsCallback:^(Statistics *statistics) {
> 
>     // CALLED WHEN SESSION GENERATES STATISTICS
> 
> }];
> ```
> 
> FFmpegKit 可以从这里下载：https://github.com/debugly/ffmpeg-kit/releases/tag/6.1.1-lts-240726170810

非常感谢，这个能实现 rtmp h264格式的 视频下载，rtmp h265的目前不行，可能需要转码才可以使用，我再看看 FFmpegKit 有没有命令行 支持转码加下载的

**Comment by debugly** [comment]
那是因为没有开启 x265 编码器

**Comment by 1996GJ** [comment]
> -i rtsp://your_rtsp_stream_url -c copy output.flv

请问 是修改 -i rtsp://your_rtsp_stream_url -c copy output.flv 这个命令么，还是需要别的操作

**Comment by debugly** [comment]
改成这样 `-i rtsp://your_rtsp_stream_url -c:v libx265 -crf 26 -preset fast output.flv` ，不过现在的 FFmpeg 没有开启 x265 编码器，所以执行肯定失败。

**Comment by 1996GJ** [comment]
> 改成这样 `-i rtsp://your_rtsp_stream_url -c:v libx265 -crf 26 -preset fast output.flv` ，不过现在的 FFmpeg 没有开启 x265 编码器，所以执行肯定失败。
是的 这种类似命令 我试过，执行都失败的。我用的还是 pod 导入的 ffmpeg-kit，不知道是不是不支持x265的功能，使用下载的 FrameWork，项目运行就会报错
