### ISSUE TITLE
【QA】关于外挂字体的设置

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#37]
大佬您好，我问一个问题，目前外挂字体如果是动态加载的字体加载不了，但是放在App里面的字体是可以的，能不能支持一下动态加载的字体加载呢？
我是这种方式，从系统的文件里面导入的字体
private func registerFont(at url: URL) -> String? {
        guard let fontDataProvider = CGDataProvider(url: url as CFURL) else {
            print("Failed to create data provider for font.")
            return nil
        }
        guard let font = CGFont(fontDataProvider) else {
            print("Failed to create CGFont object.")
            return nil
        }
        var error: Unmanaged<CFError>?
        if !CTFontManagerRegisterGraphicsFont(font, &error) {
            print("Error registering font: \(String(describing: error?.takeUnretainedValue()))")
            return nil
        }
        return font.postScriptName as String?
    }

**Comment by debugly** [comment]
首先验证下通过 CTFontManagerRegisterGraphicsFont 安装的字体成功了没？
如果确定成功注册了还不行，请把字体和字幕文件上传到GitHub。

**Comment by zdw19840929** [comment]
> 首先验证下通过 CTFontManagerRegisterGraphicsFont 安装的字体成功了没？ 如果确定成功注册了还不行，请把字体和字幕文件上传到GitHub。

我看了一下，是验证通过的，会不会是下面设置字体的时候去的Data不对呢？
ass_add_font(ass->library, tag->value,
                         (char *)st->codecpar->extradata,
                         st->codecpar->extradata_size);

[Uploading 归档.zip…]()

**Comment by debugly** [comment]
这个 ass_add_font 处理的是视频里内嵌字体的情况。
这个字体 ChillRoundFRegular.otf 的 fontName 是什么？

**Comment by zdw19840929** [comment]
> 这个 ass_add_font 处理的是视频里内嵌字体的情况。 这个字体 ChillRoundFRegular.otf 的 fontName 是什么？

fontName就是ChillRoundFRegular，我用内嵌字幕设置外挂字体也是不行的

**Comment by debugly** [comment]
是这个效果吧？这个字体名字叫 “寒蝉全圆体”。

![3323597-21 local m3u8-744189615787](https://github.com/user-attachments/assets/27ce57dc-92d1-4524-9082-5f556025ce04)

**Comment by zdw19840929** [comment]
> 是这个效果吧？这个字体名字叫 “寒蝉全圆体”。
> 
> ![3323597-21 local m3u8-744189615787](https://private-user-images.githubusercontent.com/7333743/354121480-27ce57dc-92d1-4524-9082-5f556025ce04.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTg5NDAsIm5iZiI6MTcyMjQ5ODY0MCwicGF0aCI6Ii83MzMzNzQzLzM1NDEyMTQ4MC0yN2NlNTdkYy05MmQxLTQ1MjQtOTA4Mi01ZjU1NjAyNWNlMDQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDc1MDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JjMTY3YTc4YmY4MmViNWUwOGM0NDA4N2Y0MzE0YzRhZGEyNDc0NmRkYWM0ZjU5OWM5YzFjOWU0M2ZiYTczYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0_P0_R7q3ZB86sZ5gwZOVTSXJHe72qPYc1B0BYz1ke0)

对的大佬 是这个效果

**Comment by debugly** [comment]
已经支持了，把字体放到沙河里，然后沙河路径赋值给 IJKSDLSubtitlePreference 的 FontsDir 成员变量，字体名使用 "寒蝉全圆体" 即可。

需要更新 ijk:

https://github.com/debugly/ijkplayer/releases/tag/k0.11.5-beta-240801155020

**Comment by zdw19840929** [comment]
发现一个小问题，如果默认是内嵌字幕的时候设置不成功，我需要选择一个外挂字幕或者切换一下内嵌字幕才生效

**Comment by zdw19840929** [comment]
> 已经支持了，把字体放到沙河里，然后沙河路径赋值给 IJKSDLSubtitlePreference 的 FontsDir 成员变量，字体名使用 "寒蝉全圆体" 即可。
> 
> 需要更新 ijk:
> 
> https://github.com/debugly/ijkplayer/releases/tag/k0.11.5-beta-240801155020

@debugly  发现一个小问题，如果默认是内嵌字幕的时候设置不成功，我需要选择一个外挂字幕或者切换一下内嵌字幕才生效

**Comment by debugly** [comment]
我这试了没有这个问题，我的demo里是在 prepareToPlay 之前，给 player.subtitlePreference 赋的值。

**Comment by zdw19840929** [comment]
> 我这试了没有这个问题，我的demo里是在 prepareToPlay 之前，给 player.subtitlePreference 赋的值。

@debugly  谢谢大佬的解答，我在prepareToPlay之前把FontsDir指定了一下，之后再设置就OK了
