### ISSUE TITLE
[Bug Report] 有些字幕没有展示

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#39]
大佬您好
我现在播放视频时发现有些时候会有吞字幕的现象，就是本该有字幕的地方没有展示。

![IMG_4122](https://github.com/user-attachments/assets/f21d14b5-f6e8-4e52-87e8-a91a385446d7)

![IMG_4123](https://github.com/user-attachments/assets/9cdc88f2-15fc-4e37-9677-d51178d50720)

视频链接地址如下：
https://www.alipan.com/s/we3PVKUbSWX

内嵌字幕选择简体中文

视频时间：36分24秒 -- 36分30秒

**Comment by debugly** [comment]
最新包做了修复：https://github.com/debugly/ijkplayer/releases/tag/k0.11.5-beta-240813144419

**Comment by zdw19840929** [comment]
> 最新包做了修复：https://github.com/debugly/ijkplayer/releases/tag/k0.11.5-beta-240813144419

我试了一下可以了，大佬这效率🐂
