### ISSUE TITLE
ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by tonightgarden** [debugly/ijkplayer#4]
尝试编译ios版本
git clone https://github.com/debugly/ijkplayer.git ijkplayer
cd ijkplayer
git checkout -B latest k0.9.4

cd shell
./init-any.sh ios
cd ios
[build.docx](https://github.com/debugly/ijkplayer/files/10353124/build.docx)
在执行./compile-any.sh build all 命令中build ffmpeg 阶段报这个错。 
编译信息见word，有空请帮忙看一下（对ios不熟悉，不知是不是啥配置问题）

**Comment by debugly** [comment]
很奇怪，我这是OK的。
看样子是 pkg-config 找不到 opus.pc 文件
找到 shell/apple/do-compile/ffmpeg.sh 文件，在 172 行增加 
pkg-config --libs opus
然后执行编译脚本，看下 [*] check opus 后面的日志输出内容吧。
