### ISSUE TITLE
真机无图像，只有粉色一片

### ISSUE THREAD

**Issue by m3u8playlist** [debugly/ijkplayer#42]
模拟器没有问题
真机只听到声音，图像粉色一片
型号iPhone 13 pro
系统iOS 16.6.1
![IMG_6006](https://github.com/user-attachments/assets/01e23e15-c441-4a32-9332-c2c16a6423d4)

[log.txt](https://github.com/user-attachments/files/16635521/log.txt)

**Comment by wfs498121294** [comment]
我也是 iphone12  iOS17.6

**Comment by debugly** [comment]
问题已经修复：https://github.com/debugly/ijkplayer/releases/tag/k0.11.6
