### ISSUE TITLE
Open-Sourcing the IJKMediaPlayerKit Project

### ISSUE THREAD

**Issue by pjbruce** [debugly/ijkplayer#47]
If possible, can the IJKMediaPlayerKit project be open source like ijkplayer/ios/IJKMediaPlayer/?

**Comment by debugly** [comment]
Why? What's wrong?

**Comment by pjbruce** [comment]
Your current design is very good, it saves the complicated compilation steps and is more convenient to use. Of course, it would be best if it could be open sourced.

**Comment by debugly** [comment]
Did you mean the project which compiled IJKMediaPlayerKit.framework?

**Comment by pjbruce** [comment]
Your answer is very fast, ^_^. Yes, IJKMediaPlayerKit.framework is currently installed using pod. Can it be open sourced separately?

**Comment by debugly** [comment]
I forked  the repo from https://github.com/bilibili/ijkplayer, the bilibili ijk was open sourced separately. 

And you know, my ijkplayer supported iOS/tvOS/macOS,need handle some crossplat  API by seprated files,need handle different link flags,etc.

To solve these problems,I used pod, When files are are added or deleted, just reinstall, everything will be OK.

You can find some issues form bilibili/ijkplayer which support author "Support Cocoapods", I did it !

Are you using my ijkpalyer, Can you give me a free star?
