### ISSUE TITLE
[Bug Report] iOS18上面中文字幕显示🀆🀆🀆🀆🀆这样的方块

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#51]
大佬，我把机器升级到了iOS18，发现中文字幕无法正常显示了，都显示的事🀆🀆🀆🀆🀆这样的方块

**Comment by debugly** [comment]
我还没升级，需要稍等等，最近没时间。

**Comment by zdw19840929** [comment]
> 我还没升级，需要稍等等，最近没时间。

好的 期待大佬的更新

**Comment by debugly** [comment]
这是iOS18，tvOS18, macOS15 系统修改了字体格式，换了默认位置导致的。
目前没有完美的修复办法，只能通过指定一个内嵌到App的字体作为 fallback 来解决；使用方法咱们在 https://github.com/debugly/ijkplayer/issues/37 这个问题里讨论过。

**Comment by zdw19840929** [comment]
> 这是iOS18，tvOS18, macOS15 系统修改了字体格式，换了默认位置导致的。 目前没有完美的修复办法，只能通过指定一个内嵌到App的字体作为 fallback 来解决；使用方法咱们在 #37 这个问题里讨论过。

好的，谢谢大佬的解答，这个问题我就先关掉了
