### ISSUE TITLE
【QA】播放之后马上就跳到了播放结束的监听方法里面

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#52]
大佬，我用Alist挂载webDAV的时候出了一个问题，就是播放器准备结束之后马上就跳到了播放结束的监听，这是什么问题呢？下面是log
[IJKMEDIA]ijkmp_set_inject_opaque(0x30020cf00)
[IJKMEDIA]ijkmp_set_inject_opaque()=void
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque(0x30020cf00)
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque()=void
[IJKMEDIA]ijkmp_ios_set_view(glView=0x10da5b000)
[IJKMEDIA]ijkmp_ios_set_view(glView=0x10da5b000)=void
[IJKMEDIA]ijkmp_set_data_source(url="http://guest:guest_Api789@192.168.3.6:5678/dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv")
[IJKMEDIA]ijkmp_set_data_source(url="http://guest:guest_Api789@192.168.3.6:5678/dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv")=0
[IJKMEDIA]ijkmp_prepare_async()
[IJKMEDIA]===== options =====
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : framedrop                    = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : overlay-format               = fcc-_es2
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : video-pictq-size             = 3
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : probsize                     = 30
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : min-frames                   = 30
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : subtitle                     = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : analyzeduration              = 16384
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : enable-accurate-seek         = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : max-fps                      = 30
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : start-on-prepared            = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : threaded_opens               = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : videotoolbox_hwaccel         = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : videotoolbox-max-frame-width = 3840
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : vol                          = 1024
[IJKMEDIA][FFPlayer @ 0x12f85c000] player-opts : http-pre-buffer-size         = 5242880
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : ijkapplication               = 0x30049cbe0
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : ijkiomanager                 = 4470710608
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : protocol_whitelist           = ijkio,ijkhttphook,concat,http,tcp,https,tls,file,bluray,smb2,dvd,rtmp,rtsp,rtp,srtp,udp
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : auto_convert                 = 0
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : user_agent                   = ijkplayer
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : dns_cache_clear              = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : timeout                      = 30000000
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : reconnect                    = 1
[IJKMEDIA][FFPlayer @ 0x12f85c000] format-opts : safe                         = 0
[IJKMEDIA][FFPlayer @ 0x12f85c000] codec-opts  : skip_frame                   = 0
[IJKMEDIA][FFPlayer @ 0x12f85c000] codec-opts  : skip_loop_filter             = 0
[IJKMEDIA]===================
[IJKMEDIA]ijkmp_prepare_async()=0
[IJKMEDIA][AVFormatContext @ 0x10a20e8f0] Opening 'http://guest:guest_Api789@192.168.3.6:5678/dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv' for reading
[IJKMEDIA]dns getaddrinfo uri = 192.168.3.6
[IJKMEDIA][tcp @ 0x302eb2d00] Original list of addresses:
[IJKMEDIA][tcp @ 0x302eb2d00] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302eb2d00] Interleaved list of addresses:
[IJKMEDIA][tcp @ 0x302eb2d00] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302eb2d00] Starting connection attempt to 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302eb2d00] Successfully connected to 192.168.3.6 port 5678
[IJKMEDIA]tcp did open uri = tcp://192.168.3.6:5678, ip = 192.168.3.6
[IJKMEDIA][http @ 0x10a2096b0] request: GET /dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 192.168.3.6:5678

Icy-MetaData: 1

[IJKMEDIA]dns getaddrinfo uri = 192.168.3.6
[IJKMEDIA][tcp @ 0x302e8ec00] Original list of addresses:
[IJKMEDIA][tcp @ 0x302e8ec00] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e8ec00] Interleaved list of addresses:
[IJKMEDIA][tcp @ 0x302e8ec00] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e8ec00] Starting connection attempt to 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e8ec00] Successfully connected to 192.168.3.6 port 5678
[IJKMEDIA]tcp did open uri = tcp://192.168.3.6:5678, ip = 192.168.3.6
[IJKMEDIA][http @ 0x10a2096b0] request: GET /dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=0-

Connection: close

Host: 192.168.3.6:5678

Icy-MetaData: 1

Authorization: Basic Z3Vlc3Q6Z3Vlc3RfQXBpNzg5

[IJKMEDIA]dns getaddrinfo uri = cn-beijing-data.aliyundrive.net
[IJKMEDIA][tcp @ 0x303207690] Original list of addresses:
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.34 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.33 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.38 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 223.109.32.106 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.41 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.39 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 223.109.32.105 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.35 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 2409:801e:300d:e000::9c port 443
[IJKMEDIA][tcp @ 0x303207690] Address 2409:801e:300d:e000::9d port 443
[IJKMEDIA][tcp @ 0x303207690] Interleaved list of addresses:
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.34 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 2409:801e:300d:e000::9c port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.33 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 2409:801e:300d:e000::9d port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.38 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 223.109.32.106 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.41 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.150.52.39 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 223.109.32.105 port 443
[IJKMEDIA][tcp @ 0x303207690] Address 36.155.171.35 port 443
[IJKMEDIA][tcp @ 0x303207690] Starting connection attempt to 36.155.171.34 port 443
[IJKMEDIA][tcp @ 0x303207690] Successfully connected to 36.155.171.34 port 443
[IJKMEDIA]tcp did open uri = tcp://cn-beijing-data.aliyundrive.net:443, ip = 36.155.171.34
[IJKMEDIA][http @ 0x10a2096b0] request: GET /603ef115f66180ba7a654401ad1aa8c89c950f99%2F603ef1152ff48627f4594e52a718b5199303c4df?callback=eyJjYWxsYmFja1VybCI6Imh0dHA6Ly9iajI5LmFwaS1ocC5hbGl5dW5wZHMuY29tL3YyL2ZpbGUvZG93bmxvYWRfY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJodHRwSGVhZGVyLnJhbmdlPSR7aHR0cEhlYWRlci5yYW5nZX1cdTAwMjZidWNrZXQ9JHtidWNrZXR9XHUwMDI2b2JqZWN0PSR7b2JqZWN0fVx1MDAyNmRvbWFpbl9pZD0ke3g6ZG9tYWluX2lkfVx1MDAyNnVzZXJfaWQ9JHt4OnVzZXJfaWR9XHUwMDI2ZHJpdmVfaWQ9JHt4OmRyaXZlX2lkfVx1MDAyNmZpbGVfaWQ9JHt4OmZpbGVfaWR9XHUwMDI2cGRzX3BhcmFtcz0ke3g6cGRzX3BhcmFtc31cdTAwMjZ2ZXJzaW9uPSR7eDp2ZXJzaW9ufSIsImNhbGxiYWNrQm9keVR5cGUiOiJhcHBsaWNhdGlvbi94LXd3dy1mb3JtLXVybGVuY29kZWQiLCJjYWxsYmFja1N0YWdlIjoiYmVmb3JlLWV4ZWN1dGUiLCJjYWxsYmFja0ZhaWx1cmVBY3Rpb24iOiJpZ25vcmUifQ%3D%3D&callback-var=eyJ4OmRvbWFpbl9pZCI6ImJqMjkiLCJ4OnVzZXJfaWQiOiI2ODEzN2E4YmJjNTI0YTg3YjIwY2FjNDk3NjI0NjhlOSIsIng6ZHJpdmVfaWQiOiI3ODQ1MDUwODIiLCJ4OmZpbGVfaWQiOiI2NzEyNTgyMjQzYzFjYzlmMjk0ZDRlMDA5MTE1ZGExN2NjYWYyN2ZlIiwieDpwZHNfcGFyYW1zIjoie1wiYXBcIjpcIjc2OTE3Y2NjY2Q0NDQxYzM5N[IJKMEDIA][matroska,webm @ 0x10a20e8f0] Format matroska,webm probed with size=2048 and score=100
[IJKMEDIA]dns getaddrinfo uri = 192.168.3.6
[IJKMEDIA][tcp @ 0x302e36300] Original list of addresses:
[IJKMEDIA][tcp @ 0x302e36300] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e36300] Interleaved list of addresses:
[IJKMEDIA][tcp @ 0x302e36300] Address 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e36300] Starting connection attempt to 192.168.3.6 port 5678
[IJKMEDIA][tcp @ 0x302e36300] Successfully connected to 192.168.3.6 port 5678
[IJKMEDIA]tcp did open uri = tcp://192.168.3.6:5678, ip = 192.168.3.6
[IJKMEDIA][http @ 0x10a2096b0] request: GET /dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv HTTP/1.1

User-Agent: ijkplayer

Accept: */*

Range: bytes=1913640660-

Connection: close

Host: 192.168.3.6:5678

Icy-MetaData: 1

[IJKMEDIA]st:0 removing common factor 1000000 from timebase
[IJKMEDIA]st:1 removing common factor 1000000 from timebase
[IJKMEDIA]Option safe not found.
[IJKMEDIA][matroska,webm @ 0x10a20e8f0] Before avformat_find_stream_info() pos: 5547 bytes read:7436 seeks:0 nb_streams:2
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 7(SPS), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a20efd0] Decoding VUI
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 8(PPS), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 7(SPS), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a20efd0] Decoding VUI
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 8(PPS), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 6(SEI), nal_ref_idc: 0
[IJKMEDIA][h264 @ 0x10a20efd0] nal_unit_type: 5(IDR), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a20efd0] Format yuv420p chosen by get_format().
[IJKMEDIA][h264 @ 0x10a20efd0] Reinit context to 1024x576, pix_fmt: yuv420p
[IJKMEDIA][matroska,webm @ 0x10a20e8f0] File ended prematurely
[IJKMEDIA][matroska,webm @ 0x10a20e8f0] After avformat_find_stream_info() pos: 7436 bytes read:7436 seeks:0 frames:1
[IJKMEDIA][FFPlayer @ 0x12f85c000] max_frame_duration: 10.000
[IJKMEDIA]Input #0, matroska,webm, from 'http://guest:guest_Api789@192.168.3.6:5678/dav/%E7%94%B5%E5%BD%B1/4K%E7%B3%BB%E5%88%97/007%E7%B3%BB%E5%88%97%E7%94%B5%E5%BD%B1/007%E4%B9%8B%E4%B8%80.%E8%AF%BA%E5%8D%9A%E5%A3%AB.Dr.No.1962.mkv':
[IJKMEDIA]  Metadata:
[IJKMEDIA]    encoder         : [IJKMEDIA]libebml v0.7.7 + libmatroska v0.8.1[IJKMEDIA]
[IJKMEDIA]    creation_time   : [IJKMEDIA]2009-03-21T02:51:09.000000Z[IJKMEDIA]
[IJKMEDIA]  Duration: [IJKMEDIA]01:49:50.50[IJKMEDIA], bitrate: [IJKMEDIA]N/A[IJKMEDIA]
[IJKMEDIA]  Stream #0:0[IJKMEDIA](eng)[IJKMEDIA], 1, 1/1000[IJKMEDIA]: Video: h264, 1 reference frame, yuv420p(progressive, left), 1024x576, 0/1[IJKMEDIA], SAR 1:1 DAR 16:9[IJKMEDIA], [IJKMEDIA]23.98 fps, [IJKMEDIA]23.98 tbr, [IJKMEDIA]1k tbn[IJKMEDIA] (default)[IJKMEDIA]
[IJKMEDIA]  Stream #0:1[IJKMEDIA](eng)[IJKMEDIA], 0, 1/1000[IJKMEDIA]: Audio: ac3, 48000 Hz, 6 channels, fltp[IJKMEDIA] (default)[IJKMEDIA]
[IJKMEDIA]aout_open_audio()
[IJKMEDIA]aout_open_audio:3,unsupported channels 6[IJKMEDIA]SDL_OpenAudio (6 channels, 48000 Hz)
[IJKMEDIA]aout_open_audio()
[IJKMEDIA]aout_open_audio:3,unsupported channels 4[IJKMEDIA]SDL_OpenAudio (4 channels, 48000 Hz)
[IJKMEDIA]aout_open_audio()
[IJKMEDIA][FFPlayer @ 0x12f85c000] AudioCodec: avcodec, ac3
[IJKMEDIA]aout_pause_audio(0)
[IJKMEDIA]videotoolbox hwaccel switch:on
[IJKMEDIA]try use videotoolbox accel
[IJKMEDIA][h264 @ 0x10a10da70] nal_unit_type: 7(SPS), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a10da70] Decoding VUI
[IJKMEDIA][h264 @ 0x10a10da70] nal_unit_type: 8(PPS), nal_ref_idc: 3
[IJKMEDIA][FFPlayer @ 0x12f85c000] VideoCodec: avcodec, h264
[IJKMEDIA][FFPlayer @ 0x12f85c000] fps: 23.976101 (normal)
[IJKMEDIA][FFPlayer @ 0x12f85c000] fps: 23.976101 (normal)
[IJKMEDIA]ic metadata item:encoder=libebml v0.7.7 + libmatroska v0.8.1
[IJKMEDIA]ic metadata item:creation_time=2009-03-21T02:51:09.000000Z
[IJKMEDIA]0 st metadata item:language=eng
[IJKMEDIA]1 st metadata item:language=eng
[IJKMEDIA]auto decision max buffer size:27MB
[IJKMEDIA][FFPlayer @ 0x12f85c000] set playable_duration_ms:41,cached_duration_in_ms:41
[IJKMEDIA][h264 @ 0x10a10da70] nal_unit_type: 6(SEI), nal_ref_idc: 0
[IJKMEDIA][h264 @ 0x10a10da70] nal_unit_type: 5(IDR), nal_ref_idc: 3
[IJKMEDIA][h264 @ 0x10a10da70] Format videotoolbox_vld chosen by get_format().
[IJKMEDIA][h264 @ 0x10a10da70] Format videotoolbox_vld requires hwaccel initialisation.
[IJKMEDIA]ijkmp_get_msg: FFP_MSG_PREPARED
[IJKMEDIA]ijkmp_get_meta_l
[IJKMEDIA]ijkmp_get_meta_l()=void
[IJKMEDIA]ijkmp_set_playback_rate(1.000000)
[IJKMEDIA][FFPlayer @ 0x12f85c000] Playback rate: 1.000000
[IJKMEDIA]ijkmp_set_playback_rate()=void
[IJKMEDIA]ijkmp_set_playback_volume(1.000000)
[IJKMEDIA]ijkmp_set_playback_volume()=void
播放器已准备好，可以开始播放了
[IJKMEDIA]ijkmp_start()
[IJKMEDIA]ijkmp_start()=0
[IJKMEDIA]ijkmp_get_msg: FFP_REQ_START
[IJKMEDIA][FFPlayer @ 0x12f85c000] ijkmp_get_msg: FFP_REQ_START: start on fly
[IJKMEDIA]aout_pause_audio(0)
[IJKMEDIA]aout_close_audio()
[IJKMEDIA]aout_set_volume()
[IJKMEDIA][h264 @ 0x10a10da70] Reinit context to 1024x576, pix_fmt: videotoolbox_vld
[IJKMEDIA]SDL_FFmpeg_HW_CreateOverlay(w=1024, h=576, fmt=_VTB, dp=0x3023bba20)
[IJKMEDIA]Video: first frame decoded
[IJKMEDIA]render pipeline:nv12FragmentShader,fullRange:0,matrix:BT709
[IJKMEDIA]aout_pause_audio(1)
[IJKMEDIA][FFPlayer @ 0x12f85c000] ffp_toggle_buffering: completed: OK
[IJKMEDIA]ijkmp_get_msg: FFP_MSG_COMPLETED
[IJKMEDIA]ijkmp_pause()
[IJKMEDIA]ijkmp_pause()=0
[IJKMEDIA]ijkmp_get_msg: FFP_REQ_PAUSE
[IJKMEDIA]aout_pause_audio(1)
播放销毁
[IJKMEDIA]ijkmp_stop()
[IJKMEDIA]aout_pause_audio(1)
[IJKMEDIA]IJKMetalView: videiPicture is nil
[IJKMEDIA]ijkmp_stop()=0
[IJKMEDIA]ijkmp_shutdown_l()
[IJKMEDIA]aout_pause_audio(1)
[IJKMEDIA]stream_close will close
[IJKMEDIA]will destroy avcodec:h264,flush buffers.
[IJKMEDIA]convert image convert_frame_count = 0,err = -1
[IJKMEDIA]will destroy avcodec:ac3,flush buffers.
[IJKMEDIA]aout_close_audio()
[IJKMEDIA][AVIOContext @ 0x109413930] Statistics: 7436 bytes read, 0 seeks
[IJKMEDIA]wait for video_refresh_tid
[IJKMEDIA]stream_close did close
[IJKMEDIA]ijkmp_shutdown_l()=void
[IJKMEDIA]ijkmp_set_inject_opaque(0x0)
[IJKMEDIA]ijkmp_set_inject_opaque()=void
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque(0x0)
[IJKMEDIA]ijkmp_set_ijkio_inject_opaque()=void
[IJKMEDIA]ijkmp_dec_ref(): ref=0
[IJKMEDIA]ijkmp_shutdown_l()
[IJKMEDIA]ijkmp_shutdown_l()=void
[IJKMEDIA]aout_close_audio()

**Comment by debugly** [comment]
我手边没有mac，我猜测是硬解失败了，你可以试试，把 player-opts : videotoolbox_hwaccel 设置成0

如果还不行，那可能是读包失败了，需要进一步排查。

**Comment by debugly** [comment]
监听下这个通知 IJKMPMoviePlayerPlaybackDidFinishNotification，收到后查看下userInfo里是否有错误信息，当有错误信息时表示此次结束非正常的，遇到了问题。

**Comment by zdw19840929** [comment]
大佬 我发现是什么问题了，就是URL重定向了，咱们这个SDK支持URL重定向吗？比如我用阿里云盘的webDAV功能，这时候用webDAV获取的URL会重定向，这时候SDK就会不识别了

**Comment by debugly** [comment]
重定向支持的

**Comment by zdw19840929** [comment]
> 重定向支持的

大佬这个重定向需要设置什么吗？我这边看没有获取到重定向的链接，直接就跳转到结束的方法里面了

**Comment by debugly** [comment]
不需要设置

**Comment by zdw19840929** [comment]
> 不需要设置

大佬 我发您邮箱一个地址链接，您可以看下，这个url好像无法获取重定向的地址，播放之后直接就跳到了结束的监听方法

**Comment by debugly** [comment]
周一我看看

**Comment by debugly** [comment]
我没收到

**Comment by zdw19840929** [comment]
> 我没收到

大佬我用我的Gmail又发了一遍，qianlongxu@gmail.com发到这个邮箱了，您看下收到了吗？

**Comment by debugly** [comment]
收到了，我定位下问题。

**Comment by debugly** [comment]
使用这个包试试吧：https://github.com/debugly/ijkplayer/releases/tag/k0.11.8-beta-241022092032

**Comment by debugly** [comment]
再发我个新的链接，我试试

**Comment by zdw19840929** [comment]
> 再发我个新的链接，我试试

大佬 我把视频地址发您邮箱了，您可以看下

**Comment by debugly** [comment]
我这 synology.me 的域名无法解析

**Comment by zdw19840929** [comment]
> 我这 synology.me 的域名无法解析

如果您用真机调试的话可以用5G，因为我这个域名是绑定的IPv6，所以好多网络解析不了😂

**Comment by debugly** [comment]
再试试最新包。

**Comment by zdw19840929** [comment]
> 再试试最新包。

谢谢大佬，这个已经可以啦
