### ISSUE TITLE
安卓可以用吗

### ISSUE THREAD

**Issue by 360060316** [debugly/ijkplayer#6]
安卓可以用吗

**Comment by 360060316** [comment]
我只要修改好的ffmepg 5.1也可以

**Comment by debugly** [comment]
安卓上没有测试过，可能跑不起来。

ffmpeg 没有编译安卓平台的，只有iOS和macOS的。

**Comment by debugly** [comment]
Duplicate of https://github.com/debugly/ijkplayer/issues/48
