### ISSUE TITLE
滑动进度条的时候获取当前帧预览画面？能加下这个功能吗？

### ISSUE THREAD

**Issue by huaibaobao2017** [debugly/ijkplayer#7]
IJKMPMoviePlayerAfterSeekFirstVideoFrameDisplayNotification 这个通知是seek后才能获取

**Comment by debugly** [comment]
是的，每次seek之后并且是解码第一帧才会收到这个通知。
刚加载视频，解码后收到的是 IJKMPMoviePlayerFirstVideoFrameDecodedNotification 。

**Comment by debugly** [comment]
你说的是获取指定位置的缩略图吧，目前没有这个功能，后续考虑下。
