### ISSUE TITLE
内嵌字幕没有展示，手动调用exchangeSelectedStream无效，切换音轨倒是正常。

### ISSUE THREAD

**Issue by huaibaobao2017** [debugly/ijkplayer#8]
已开启subtitle, options?.setPlayerOptionIntValue(1, forKey: "subtitle") 看源码默认已经开启了？但是没有效果

{
    "codec_name" = hevc;
    "fps_den" = 1001;
    "fps_num" = 24000;
    height = 2160;
    "sar_den" = 1;
    "sar_num" = 1;
    "stream_idx" = 0;
    "tbr_den" = 1001;
    "tbr_num" = 24000;
    type = video;
    width = 3840;
},
{
    "codec_name" = truehd;
    language = eng;
    "sample_rate" = 48000;
    "stream_idx" = 1;
    title = "TrueHD 7.1 Atmos";
    type = audio;
},
{
    "codec_name" = dts;
    language = eng;
    "sample_rate" = 48000;
    "stream_idx" = 2;
    title = "DTS-HD MA 7.1";
    type = audio;
},
{
    bitrate = 640000;
    "codec_name" = ac3;
    language = eng;
    "sample_rate" = 48000;
    "stream_idx" = 3;
    title = "DD 5.1";
    type = audio;
},
{
    bitrate = 320000;
    "codec_name" = ac3;
    language = eng;
    "sample_rate" = 48000;
    "stream_idx" = 4;
    title = "DD 2.0";
    type = audio;
},
{
    bitrate = 640000;
    "codec_name" = ac3;
    language = fre;
    "sample_rate" = 48000;
    "stream_idx" = 5;
    title = "DD 5.1";
    type = audio;
},
{
    bitrate = 1024000;
    "codec_name" = eac3;
    language = spa;
    "sample_rate" = 48000;
    "stream_idx" = 6;
    title = "DDP 7.1";
    type = audio;
},
{
    bitrate = 1024000;
    "codec_name" = eac3;
    language = jpn;
    "sample_rate" = 48000;
    "stream_idx" = 7;
    title = "DDP 7.1";
    type = audio;
},
{
    "codec_name" = subrip;
    language = eng;
    "stream_idx" = 8;
    type = timedtext;
},
{
    "codec_name" = subrip;
    language = eng;
    "stream_idx" = 9;
    title = SDH;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = eng;
    "stream_idx" = 10;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = fre;
    "stream_idx" = 11;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = spa;
    "stream_idx" = 12;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = jpn;
    "stream_idx" = 13;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = fre;
    "stream_idx" = 14;
    title = FORCED;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = spa;
    "stream_idx" = 15;
    title = FORCED;
    type = timedtext;
},
{
    "codec_name" = "hdmv_pgs_subtitle";
    language = jpn;
    "stream_idx" = 16;
    title = FORCED;
    type = timedtext;
}
)

**Comment by huaibaobao2017** [comment]
更新！

**Comment by huaibaobao2017** [comment]
0.10.4 版本，特效字幕文字很小，普通字幕显示正常。{
"codec_name" = "hdmv_pgs_subtitle";
language = eng;
"stream_idx" = 10;
type = timedtext;
},
{
"codec_name" = "hdmv_pgs_subtitle";
language = fre;
"stream_idx" = 11;
type = timedtext;
},

**Comment by debugly** [comment]
好的，明天我看下。

**Comment by debugly** [comment]
@huaibaobao2017  k0.10.5 版本没有修改字幕相关的代码，不会影响字幕大小的。
目前还不能做到文本字幕和特效字幕大小统一，所以字幕功能需要提供一个供用户修改大小的交互。
通过调整 IJKSDLSubtitlePreference 的 ratio 可以修改字幕大小包括特效字幕和普通文本字幕。
