### ISSUE TITLE
大佬帮忙看看这个报错是什么原因

### ISSUE THREAD

**Issue by zdw19840929** [debugly/ijkplayer#9]
大佬帮忙看看这个报错是什么原因，谢谢啦 @debugly 
<img width="1135" alt="截屏2024-03-05 11 11 55" src="https://github.com/debugly/ijkplayer/assets/4941590/01e75cdf-da5c-42fc-ada7-a031a75fa60b">

**Comment by zdw19840929** [comment]
还有一个问题就是最新的k0.10.5不显示内嵌字幕

**Comment by debugly** [comment]
> 大佬帮忙看看这个报错是什么原因，谢谢啦 @debugly <img alt="截屏2024-03-05 11 11 55" width="1135" src="https://private-user-images.githubusercontent.com/4941590/309970152-01e75cdf-da5c-42fc-ada7-a031a75fa60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTkyNDQsIm5iZiI6MTcwOTYxODk0NCwicGF0aCI6Ii80OTQxNTkwLzMwOTk3MDE1Mi0wMWU3NWNkZi1kYTVjLTQyZmMtYWRhNy1hMDMxYTc1ZmE2MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDYwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzZWI4ZjRjYzAxNTg5MjE5Mjc1Y2Y1ZTBlMjM2OTk4Mzk5ZDUzMTNmOTFlMTRkNDc3ODg0MzUyOGM1MmFmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8e8ZD840fQvic3pi25SpEmJSBIARpitFnmMcxoEQcS0">

这个问题是缺少了 dvdread 三方库，
如果运行的是 iOS 的demo 可以通过下面的步骤安装：
cd shell && ./install-pre-any.sh  ios
如果运行的是 macOS 的demo 可以通过下面的步骤安装：
cd shell && ./install-pre-any.sh  macos
如果两个平台的demo都需要运行，则可以：
cd shell && ./install-pre-any.sh  all

**Comment by debugly** [comment]
> 还有一个问题就是最新的k0.10.5不显示内嵌字幕

把 IJKMetalView.m 文件的第 583 行改成：
`
self.backingScaleFactor = self.window.contentScaleFactor;
`

**Comment by zdw19840929** [comment]
可以啦，谢谢大佬Thanks♪(･ω･)ﾉ @debugly
